# CONFIGURACION PARA INTELLIJ (LOCAL)
spring.datasource.url=jdbc:mysql://localhost:3306/proyecto_3d_jpa?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345678

# Mantener el resto igual
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true